language: go

go:
  - 1.9.x
  - 1.10.x
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - sudo apt-get install -y nodejs

install:
  - npm install

script:
  - npm test

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
