language: go

go:
  - 1.9.x
  - 1.10.x
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - npm install

script:
  - npm test

addons:
  apt:
    packages:
    - google-chrome-stable
    - nodejs
